name: CI - Proxy Test

# 実行トリガーの定義
on:
  push:
    branches:
      - main
  workflow_dispatch: # これが無いとGithub画面上で押すボタンが機能しない？？？イメージ

jobs:
  test:
    name: Run Egress Proxy Test
    runs-on: ubuntu-latest

    steps:
      - name: 1. リポジトリのチェックアウト # ここでリポジトリ上のファイルをUbuntuにチェックアウトする
        uses: actions/checkout@v4

      - name: 1.5. JSONをSquid用のテキストリンクへ変換 # チェックアウトより後に実行しないと、JSONファイルがUbuntuにないのでパニック起こす
        run: |
          # A用のJSONをテキストに変換
          # jqコマンドで"allowed_domains"の中身だけ取り出してテキストへ変換
          jq -r '.allowed_domains[]' allow-list-a.json > allow-list-a.txt

          echo "--- 生成されたallow-list-a.txtの中身をデバッグ出力 ---"
          cat allow-list-a.txt

          # B用のJSONをテキストに変換
          # jqコマンドで"allowed_domains"の中身だけ取り出してテキストへ変換
          jq -r '.allowed_domains[]' allow-list-b.json > allow-list-b.txt

          echo "--- 生成されたallow-list-b.txtの中身をデバッグ出力 ---"
          cat allow-list-b.txt
          
      
      - name: 2. Docker Compose
        run: |
          # proxy-a,proxy-bをそれぞれバックグラウンドで起動
          docker compose up --build -d proxy-a proxy-b

          docker compose run --rm app-a
          docker compose run --rm app-b

          docker compose down        
